authors:
  casper:
    name: Casper Yeh
    description: Creator
    avatar: https://avatars.githubusercontent.com/iapsekian
    url: https://github.com/iapsekian
  vivien:
    name: Vivien Lin
    description: Community support
    avatar: https://avatars.githubusercontent.com/u/4134224
    url: https://github.com/alexvoss